FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# Install Python packages
RUN pip install --no-cache-dir \
    dvc[s3]==3.50.0 \
    mlflow==2.11.0 \
    dagshub==0.3.25

WORKDIR /workspace

# DVC and Git config will be mounted
VOLUME ["/workspace"]

CMD ["bash"]
