stages:
    ingest:
        cmd: >
            docker run --rm
            -u $HOST_UID:$HOST_GID
            -v $PROJECT_PATH/data:/data
            mlops-ingest
            python ingest.py
        deps:
            - stages/ingest/ingest.py
        outs:
            - data/raw/iris.csv

    preprocess:
        cmd: >
            docker run --rm
            -u $HOST_UID:$HOST_GID
            -v $PROJECT_PATH/data:/data
            mlops-preprocess
            python preprocess.py
        deps:
            - stages/preprocess/preprocess.py
            - data/raw/iris.csv
        outs:
            - data/processed/train.csv
            - data/processed/test.csv

    train:
        cmd: >
            docker run --rm
            -u $HOST_UID:$HOST_GID
            -v $PROJECT_PATH/data:/data
            -v $PROJECT_PATH/models:/models
            -v $PROJECT_PATH:/workspace:ro
            -e MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
            -e MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME
            -e MLFLOW_TRACKING_PASSWORD=$MLFLOW_TRACKING_PASSWORD
            mlops-train
            python train.py
        deps:
            - stages/train/train.py
            - data/processed/train.csv
            - data/processed/test.csv
        params:
            - train.n_estimators
            - train.max_depth
            - train.random_state
        outs:
            - models/model_metadata.json

    evaluate:
        cmd: >
            docker run --rm
            -u $HOST_UID:$HOST_GID
            -v $PROJECT_PATH/data:/data
            -v $PROJECT_PATH/models:/models
            -v $PROJECT_PATH/metrics:/metrics
            -e MLFLOW_TRACKING_URI=$MLFLOW_TRACKING_URI
            -e MLFLOW_TRACKING_USERNAME=$MLFLOW_TRACKING_USERNAME
            -e MLFLOW_TRACKING_PASSWORD=$MLFLOW_TRACKING_PASSWORD
            mlops-evaluate
            python evaluate.py
        deps:
            - stages/evaluate/evaluate.py
            - data/processed/test.csv
            - models/model_metadata.json
        metrics:
            - metrics/metrics.json:
                  cache: false
        plots:
            - metrics/confusion_matrix.json:
                  cache: false
                  template: confusion
