mlflow:
  tracking_password: ${MLFLOW_TRACKING_PASSWORD}
  tracking_uri: ${MLFLOW_TRACKING_URI}
  tracking_username: ${MLFLOW_TRACKING_USERNAME}
preprocess:
  random_state: 42
  test_size: 0.2
train:
  max_depth: 5
  n_estimators: 100
  random_state: 42
